[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "yarn railway:build"

[deploy]
startCommand = "yarn railway:start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300
numReplicas = 1

[service]
internal_port = 3000
auto_deploy = true 